EC-USGS/pywatershed

autotest/test_canopy.py, pynhm/atmosphere/AtmBoundaryLayer.py, pynhm/base/storageUnit.py, pynhm/canopy/PRMSCanopy.py
* not really working yet, but tests should pass
* need comparison with intcp_stor, which is not saved yet for drb 2 year
=> feat(canopy): first canopy implementation for new framework

autotest/test_canopy.py, autotest/test_groundwater.py, pynhm/base/adapter.py, pynhm/base/storageUnit.py, pynhm/hydrology/PRMSCanopy.py, pynhm/hydrology/PRMSGroundwater.py
* moved Variable -> Adapter
* changed staticmethod StorageUnit.get_input_variables() to StorageUnit.get_inputs() 
* changed the property StorageUnit.input_variables to StorageUnit.inputs
* defined StorageUnit.set_initial_conditions(self) in the super and implemented in canopy and groundwater
=> Refactor(storage adapter)

autotest/test_meta.py, autotest/test_snow.py, pynhm/atmosphere/NHMSolarGeometry.py, pynhm/base/adapter.py, pynhm/base/control.py, pynhm/base/meta.py, pynhm/base/storageUnit.py, pynhm/constants.py, pynhm/hydrology/PRMSCanopy.py, pynhm/hydrology/PRMSGroundwater.py, pynhm/hydrology/PRMSSnow.py, pynhm/static/metadata/variables.yaml, pynhm/utils/netcdf_utils.py, pynhm/utils/time_utils.py
* soltab_horad_potsw adapted (custom subclass)
* init variable from metadata
* control time methods/properties from time_utils (untested)
=> snow dummy advance:

autotest/test_runoff.py, pynhm/hydrology/PRMSRunoff.py, test_data/common/control.multi_hru, test_data/common/control.single_hru
* comparison test does not pass yet
* depression storage not implemented yet
=> revamping runoff again

autotest/test_runoff.py, pynhm/hydrology/PRMSRunoff.py
* not working yet so comparison checking is turned off
=> add depression storage to runoff

autotest/test_canopy_runoff.py, pynhm/base/adapter.py, pynhm/base/storageUnit.py, pynhm/hydrology/PRMSRunoff.py
* implement minor helper method set_input_to_adapter()
* demonstrate how to wire up output from one box as input to another box
=> feat(canopy-runoff): wire up output from canopy as input to runoff

.github/workflows/ci.yaml
Use Wes' github-action for gfort instead of rolling our own (which is mired in failure).
Thanks, @w-bonelli!
=> Fix CI macos-latest gfortran issues  

.github/workflows/ci_examples.yaml, autotest/test_cbh_to_netcdf.py, autotest/test_param_separate.py, examples/01_automated_testing.ipynb, pynhm/hydrology/PRMSSnow.py, pynhm/static/metadata/variables.yaml, pynhm/utils/cbh_utils.py, pynhm/utils/netcdf_utils.py
=> Feat(cbh to netcdf)

autotest/test_atmosphere.py, autotest/test_model.py, autotest/test_netcdf_output.py, autotest/test_solar_geom.py, pynhm/atmosphere/PRMSAtmosphere.py, pynhm/atmosphere/PRMSSolarGeometry.py, pynhm/base/control.py, pynhm/base/storageUnit.py, pynhm/base/timeseries.py
with some fixes to TimeseriesArray advancing
=> Consolidated netcdf writes for Atmosphere and SolarGeom

ci/requirements/doc.yml, ci/requirements/environment.txt, ci/requirements/environment.yml, ci/requirements/pwsmf6nb.yml
move to xarray@main instead of custom branch with xr [#7739](https://github.com/pydata/xarray/pull/7739), next release until we can conda/pip install xarray
=> change xarray dep

README.md
Minor update to install procedures in README.md
=> Doc update readme

doc/whats-new.rst
This is the final PR to develop for v0.2.0 release
=> finalize whats new for release

.github/RELEASE.md, DEVELOPER.md, README.md, doc/index.rst, doc/whats-new.rst
=> Feat prep release

.github/RELEASE.md, asv_benchmarks/benchmarks/prms.py, asv_benchmarks/run_benchmarks_wo_asv.py, pywatershed/base/model.py
This catches ASV up with breaking changes
=> Asv for release

.github/scripts/update_version.py, CITATION.cff
previously `__pakname__`, `__author__` and `__author_email__` were overwritten from `version.py`
=> fix update_version.py: read authors from CITATION.cff, write to version.py

.github/PULL_REQUEST_TEMPLATE.md, environment.yml, environment_w_jupyter.yml
env details, partly bc all new issues with jupyter_contrib_nbextensions
=> Bugfix v0.2.1

README.md, doc/whats-new.rst
=> add conda badges for new conda feedstock, update installation procedures

.github/scripts/symlink_gfortran_mac.sh, .github/workflows/ci.yaml, .github/workflows/ci_examples.yaml
* forgot the repo ownership change in #242
=> ci: fix awvwgk/setup-fortran -> fortran-lang/setup-fortran

.github/workflows/release.yaml
=> update release.yaml to follow ci.yaml for model CI

environment.yml, environment_w_jupyter.yml, examples/sagehen/environment.yaml, pyproject.toml
https://github.com/pytest-dev/pytest/releases/tag/8.1.0 broke some plugins and was yanked
=> chore(dependencies): restrict yanked pytest version 8.1.0

.github/workflows/ci.yaml, environment.yml, environment_w_jupyter.yml, pyproject.toml, pywatershed/base/model.py, pywatershed/hydrology/prms_snow.py, pywatershed/hydrology/prms_soilzone.py
=> data release with minor changes

.github/workflows/ci.yaml, .github/workflows/ci_examples.yaml, autotest/test_mmr_to_mf6_dfw.py, autotest/test_obsin_flow_node.py, autotest_exs/test_notebooks.py, environment.yml, environment_w_jupyter.yml, examples/06_flow_graph_starfit.ipynb, examples/07_mmr_to_mf6_chf_dfw.ipynb, pyproject.toml, pywatershed/utils/mmr_to_mf6_dfw.py, readthedocs.yml
some other pyproject and env fixes
=> fix mmr to dfw, renaming swf to chf;

CITATION.cff, doc/index.rst, doc/whats-new.rst
=> update release dates for v2.0

pyproject.toml
=> fix pyproject.toml classifiers, hopefully for conda noarch fix

autotest/test_netcdf_read.py, autotest/test_preprocess_csv.py, autotest/test_prms_parameters.py, pywatershed/analysis/model_graph.py, pywatershed/analysis/process_plot.py, pywatershed/parameters/starfit_parameters.py, pywatershed/utils/mmr_to_mf6_dfw.py, pywatershed/utils/utils.py
=> ruff and ProcessPlot kwargs to hvplot

environment.yml, environment_w_jupyter.yml
=> pin holoviews as the new version breaks things

.github/workflows/ci.yaml, .github/workflows/ci_examples.yaml, .github/workflows/release.yaml, autotest/ci_local.sh, examples/07_mmr_to_mf6_chf_dfw.ipynb
Just invoke the [codegen utility](https://flopy.readthedocs.io/en/latest/md/generate_classes.html) directly
=> don't use update_flopy.py
